### ISSUE TITLE
Building aarch64 fails

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/Pengwin-Enterprise#15]
```
sudo livemedia-creator --make-tar --iso=/tmp/install.iso --image-name=install.tar.xz --ks=install.ks
```
at https://github.com/WhitewaterFoundry/WLE/blob/master/create-targz.sh#L39

experiences critical error

logs show anaconda cannot find package vim-minimal
at https://gist.github.com/sirredbeard/931b69c6d52a52ea907ce3cfdf34a7fb#file-gistfile1-txt-L1183

kickstart files says to install vim-minimal
at https://github.com/CentOS/sig-cloud-instance-build/blob/master/docker/centos-7arm64.ks#L42

commenting out vim-minimal in kickstart file just produces can't find systemd, other packages, etc.

packages seem to be in repo linked by kickstart file
at http://mirror.centos.org/altarch/7/updates/aarch64/Packages/

yet it cannot find them

perhaps anaconda cannot locate because no tree file?
```
ERR packaging:got HTTP Error 404 when downloading [.]treeinfo files
```
at https://gist.github.com/sirredbeard/931b69c6d52a52ea907ce3cfdf34a7fb#file-gistfile1-txt-L1183

**Comment by grufwub** [comment]
I had a look through the Anaconda logs and I have some ideas that I'm going to give a go regarding this, including setting another editor to install, setting some other related packages to install in case they aren't for whatever reason among other things. Will post back when I have answers!

**Comment by Biswa96** [comment]
Anyone tried using CI e.g. TravisCI or AppveyorCI?

**Comment by ThatWeirdAndrew** [comment]
Trying to set one up. Could anyone help me with docker? I'm new to this.

**Comment by sirredbeard** [comment]
When it comes down it you can also just build the aarch64 images on a Scaleway aarch64 VPS if needed.

**Comment by Biswa96** [comment]
Yes, ARM64 docker images can be build in X64 machine. Just need qemu interpreter to be passed in command.

**Comment by crramirez** [comment]
We have no plans for now to have Pengwin Enterprise on ARM64. Closing this for now
