### ISSUE TITLE
wsl2 can be used at the same time with Vmware workstation ?

### ISSUE THREAD

**Issue by weinformatics** [WhitewaterFoundry/Pengwin-Enterprise#55]
wsl2 can be used at the same time with Vmware workstation ?

**Comment by crramirez** [comment]
I haven't tested, but I think that no. Because it uses Hyper-V virtualization at some point and it may conflict with Vmware

**Comment by weinformatics** [comment]
> I haven't tested, but I think that no. Because it uses Hyper-V virtualization at some point and it may conflict with Vmware

@crramirez Many thanks for your reply !!! If so I will hope the WSL1 can support docker, since both centos and docker will have its own update and more new features.

**Comment by crramirez** [comment]
You'll need to install Docker Desktop for Windows, and you can install the docker client in WSL1. Soon WSL2 will support docker natively.

Mmm ok but you'll still need Vmware right? if it is the case, no you can't install docker daemon on WSL1 you'll need Docker Desktop which is Hyper-V based.

What about putting all your services in vmware? You can create a Linux box with docker. Also you can use Docker Toolbox. Or simply use docker-machine with a vmware backend.
