### ISSUE TITLE
Error During Oracle Xe installation

### ISSUE THREAD

**Issue by jmolinas** [WhitewaterFoundry/Pengwin-Enterprise#56]
encounter error during oracle 18c xe installation
`/opt/oracle/product/18c/dbhomeXE/oui/bin/runInstaller.sh: line 3:  3517 Segmentation fault      (core dumped) ./runInstaller $*
/opt/oracle/product/18c/dbhomeXE/oui/bin/runInstaller.sh: line 3:  3522 Segmentation fault      (core dumped) ./runInstaller $*
[SEVERE] An error occurred while registering the Oracle home. Verify logs in /var/log/oracle-database-xe-18c/results/oraInstall.log and /opt/oracle/oraInventory for more details and try again.`

**Comment by crramirez** [comment]
Hello,

I think that installing Oracle XE in WSL can lead to multiple problems. Maybe with WSL 2. I recommend you to use docker for this. Oracle has prebuilt images for this

Regards
