### ISSUE TITLE
Pengwin Enterprise email is down

### ISSUE THREAD

**Issue by devlocalca** [WhitewaterFoundry/Pengwin-Enterprise#59]
**Describe the bug**
On the Windows Store WSL page for Pengwin Linux, you advertise to contact: ### **enterprise@whitewaterfoundry.com**

When I email that address, it bounces.

WHY??? JESUS!!!

JESUS

**Comment by crramirez** [comment]
We will look into that

**Comment by crramirez** [comment]
We made the corrections, and now you shouldn't have any problems to send us an email. Thanks for reporting
