### ISSUE TITLE
/boot/grub/grub.conf not present. 

### ISSUE THREAD

**Issue by gao4263** [WhitewaterFoundry/Pengwin-Enterprise#66]
I install oracle database 19c on pengwin-enterprise oracle linux , It report  missing  /boot/grub/grub.conf  , how to resolve it

**Comment by crramirez** [comment]
Let's check how to solve it. It doesn't include it by definition. Is it failing to install the database?

**Comment by gao4263** [comment]
> Let's check how to solve it. It doesn't include it by definition. Is it failing to install the database?

yes ,it failed,  I buy  pengwin-enterprise  just to install oracle database 19c , pls help me

**Comment by crramirez** [comment]
Hello,

I could configure Oracle database using these instructions: https://oracle-base.com/articles/19c/oracle-db-19c-rpm-installation-on-oracle-linux-7

But only in WSL2, in WSL1 it shows a shared memory error

Hope it helps

Regards,
Carlos
